### ISSUE TITLE
Pass options to build from configuration

### ISSUE THREAD

**Issue by dantleech** [massiveart/MassiveBuildBundle#8]
It should be possible to define both global and per-target configuration options.

```
targets:
     rebuild:
         options: { destroy: true }
         dependencies:
             database: ~
             user: { recreate: true }
```
